In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
df = pd.read_csv(r'C:/Users/Admin/Downloads/diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
df.duplicated().sum()

0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [6]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [7]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [8]:
df.mean()

Pregnancies                   3.845052
Glucose                     120.894531
BloodPressure                69.105469
SkinThickness                20.536458
Insulin                      79.799479
BMI                          31.992578
DiabetesPedigreeFunction      0.471876
Age                          33.240885
Outcome                       0.348958
dtype: float64

In [9]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [10]:
df.rename(columns={"Outcome":'Diabetic'},inplace=True)

In [12]:
X=df[['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'Age']]
y=df['Diabetic']

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.33)

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
from sklearn.metrics import classification_report

In [17]:
lr=LogisticRegression()

In [18]:
lr.fit(X_train, y_train)

LogisticRegression()

In [19]:
X.columns

Index(['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'Age'], dtype='object')

In [20]:
lr.coef_

array([[ 0.03815491, -0.01581401,  0.0061572 , -0.00128393,  0.08103484,
         0.04096227]])

In [21]:
predictions=lr.predict(X_test)

In [22]:
from sklearn import metrics

In [23]:
metrics.mean_absolute_error(y_test,predictions)

0.2637795275590551

In [24]:
metrics.mean_squared_error(y_test,predictions)

0.2637795275590551

In [25]:
from sklearn.model_selection import cross_val_score

In [26]:
cross_val_score(LogisticRegression(), X, y, cv=5, scoring='accuracy')

array([0.78571429, 0.75974026, 0.72727273, 0.80392157, 0.78431373])

In [27]:
logRegAcc=cross_val_score(LogisticRegression(), X, y, cv=5, scoring='accuracy').mean()
logRegAcc

0.7721925133689839

In [28]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [29]:
y_pred = model.predict(X_test)

In [30]:
print(classification_report(y_test, y_pred, digits=2))

              precision    recall  f1-score   support

           0       0.74      0.87      0.80       156
           1       0.72      0.52      0.60        98

    accuracy                           0.74       254
   macro avg       0.73      0.70      0.70       254
weighted avg       0.73      0.74      0.73       254



In [31]:
X.shape

(768, 6)

In [32]:
import pickle

In [33]:
pickle.dump(model,open('Modeldb.pkl','wb'))

In [35]:
loaded_model = pickle.load(open('Modeldb.pkl','rb'))
loaded_model

LogisticRegression()

In [36]:
loaded_model.predict([[44,34,1,5,4,61]])

array([0], dtype=int64)

In [37]:
probability = loaded_model.predict_proba([[44,34,1,5,4,61]])
probability

array([[0.98885217, 0.01114783]])

In [38]:
probability = np.round((np.max(probability) * 100),2)
probability

98.89

In [39]:
type(probability)

numpy.float64